"""empty message

Revision ID: 10c728f8e676
Revises: 5949380c8c48
Create Date: 2015-10-14 13:07:10.321652

"""

# revision identifiers, used by Alembic.
revision = '10c728f8e676'
down_revision = '5949380c8c48'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
