"""empty message

Revision ID: 1279d881b4cf
Revises: 3831a354f325
Create Date: 2015-10-13 16:18:44.588548

"""

# revision identifiers, used by Alembic.
revision = '1279d881b4cf'
down_revision = '3831a354f325'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
