"""empty message

Revision ID: 159ed5fbcccc
Revises: 33f4cda3c0bf
Create Date: 2015-12-16 12:30:32.316000

"""

# revision identifiers, used by Alembic.
revision = '159ed5fbcccc'
down_revision = '33f4cda3c0bf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
