"""empty message

Revision ID: 1e61d380dcd9
Revises: 1279d881b4cf
Create Date: 2015-10-14 10:01:39.079920

"""

# revision identifiers, used by Alembic.
revision = '1e61d380dcd9'
down_revision = '1279d881b4cf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
