"""empty message

Revision ID: 1f249eadb14
Revises: 27ca60a84b4f
Create Date: 2015-11-13 22:09:59.622000

"""

# revision identifiers, used by Alembic.
revision = '1f249eadb14'
down_revision = '27ca60a84b4f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('remark', sa.Unicode(length=120), nullable=True))
    op.drop_column('answer', 'description')
    op.add_column('question', sa.Column('remark', sa.Unicode(length=120), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'remark')
    op.add_column('answer', sa.Column('description', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('answer', 'remark')
    ### end Alembic commands ###
