"""empty message

Revision ID: 203963d2c9d1
Revises: 44225f3971ce
Create Date: 2015-11-06 10:29:17.107000

"""

# revision identifiers, used by Alembic.
revision = '203963d2c9d1'
down_revision = '44225f3971ce'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('recycle_max_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('recycle_min_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('exchange_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], [u'product.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price')
    ### end Alembic commands ###
