"""empty message

Revision ID: 216b3571df6c
Revises: 5609a472e85
Create Date: 2015-12-15 20:42:50.683000

"""

# revision identifiers, used by Alembic.
revision = '216b3571df6c'
down_revision = '5609a472e85'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=128), nullable=False))
    op.drop_column('user', '_password')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('_password', mysql.VARCHAR(length=128), nullable=False))
    op.drop_column('user', 'password')
    ### end Alembic commands ###
