"""empty message

Revision ID: 27ca60a84b4f
Revises: 4d8b6294949e
Create Date: 2015-11-06 10:51:59.244000

"""

# revision identifiers, used by Alembic.
revision = '27ca60a84b4f'
down_revision = '4d8b6294949e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
