"""empty message

Revision ID: 3831a354f325
Revises: 3af584d8864f
Create Date: 2015-10-12 23:32:22.048428

"""

# revision identifiers, used by Alembic.
revision = '3831a354f325'
down_revision = '3af584d8864f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
