"""empty message

Revision ID: 3af584d8864f
Revises: None
Create Date: 2015-08-03 11:15:34.564920

"""

# revision identifiers, used by Alembic.
revision = '3af584d8864f'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answer', 'content',
               existing_type=mysql.VARCHAR(length=60),
               nullable=False)
    op.add_column('manufacturer', sa.Column('logo', sa.Unicode(length=200), nullable=True))
    op.alter_column('manufacturer', 'name',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.add_column('product', sa.Column('photo', sa.Unicode(length=200), nullable=True))
    op.alter_column('question', 'content',
               existing_type=mysql.VARCHAR(length=60),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question', 'content',
               existing_type=mysql.VARCHAR(length=60),
               nullable=True)
    op.drop_column('product', 'photo')
    op.alter_column('manufacturer', 'name',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.drop_column('manufacturer', 'logo')
    op.alter_column('answer', 'content',
               existing_type=mysql.VARCHAR(length=60),
               nullable=True)
    ### end Alembic commands ###
