"""empty message

Revision ID: 44225f3971ce
Revises: 3a7873c369fa
Create Date: 2015-11-06 10:17:18.797000

"""

# revision identifiers, used by Alembic.
revision = '44225f3971ce'
down_revision = '3a7873c369fa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
