"""empty message

Revision ID: 4d8b6294949e
Revises: 50ce6655d57d
Create Date: 2015-11-06 10:42:05.287000

"""

# revision identifiers, used by Alembic.
revision = '4d8b6294949e'
down_revision = '50ce6655d57d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
