"""empty message

Revision ID: 50ce6655d57d
Revises: 203963d2c9d1
Create Date: 2015-11-06 10:34:09.487000

"""

# revision identifiers, used by Alembic.
revision = '50ce6655d57d'
down_revision = '203963d2c9d1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'price')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=True))
    ### end Alembic commands ###
