"""empty message

Revision ID: 5609a472e85
Revises: 1f249eadb14
Create Date: 2015-12-15 20:06:13.765000

"""

# revision identifiers, used by Alembic.
revision = '5609a472e85'
down_revision = '1f249eadb14'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('_password', sa.String(length=128), nullable=False))
    op.drop_column('user', 'password')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=80), nullable=False))
    op.drop_column('user', '_password')
    ### end Alembic commands ###
