"""empty message

Revision ID: 57f2ff747d31
Revises: 159ed5fbcccc
Create Date: 2015-12-16 12:31:55.747000

"""

# revision identifiers, used by Alembic.
revision = '57f2ff747d31'
down_revision = '159ed5fbcccc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
