"""empty message

Revision ID: 5949380c8c48
Revises: 1e61d380dcd9
Create Date: 2015-10-14 12:34:44.313251

"""

# revision identifiers, used by Alembic.
revision = '5949380c8c48'
down_revision = '1e61d380dcd9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
